version: '3.5'
services:
  milvus:
    image: milvusdb/milvus:v2.3.9
    container_name: milvus-standalone
    ports:
      - "19530:19530"
      - "9091:9091"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: gemma3n-app
    ports:
      - "8050:8050"
    depends_on:
      milvus:
        condition: service_healthy
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050/"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ollama_data: 